### ISSUE TITLE
Updating BaseX

### ISSUE THREAD

**Issue by kristiank** [Quodatum/openshift-basex-quick-start#6]
I set up BaseX on OpenShift some long time ago using this quick-start (thank you!). It seems that the version of BaseX has been bumped since then. What do I need to do to update my BaseX? If the command ```git pull -s recursive -X theirs upstream master``` is meant for doing that, I can't figure out what to replace the ```theirs upstream master``` string with.

**Comment by kristiank** [comment]
I now found the configure file and was able to very easily change the version. But how should I proceed to update everything according to your openshift-basex-quick-start git, shouldn't there be a sequence of git commands for this?

**Comment by apb2006** [comment]
Editing the `config` file to set the basex version and then using `git
commit` and   `git push` is the way to change the basex version.
However this will also reset  any Basex databases  and user information to
that found in your git repo.

If this is a problem you may wish to take a backup of any databases  first.
perhaps by using the DBA app and then scp/sftp to save the files.

I would recommend creating a new openshift application instance with the
desired basex version and your code first, then migrate any required data
after that.

**Comment by kristiank** [comment]
But is there no way of git pulling your quick-start to synchronize other changes (like saxonhe=9.7.15, chop=false etc) and merging/pushing these to my instance?

**Comment by apb2006** [comment]
I think this is just a git issue. You want to merge changes but keep your additions.
It is not something I have tried or could try at the moment. But does not 
`git pull -s recursive -X theirs upstream master`
take you down that road?
